# Generated by Django 5.2.8 on 2025-11-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
